### ISSUE TITLE
CLN v24: Does this work for anyone?

### ISSUE THREAD

**Issue by ghost** [giovannizotta/circular#20]
I have circular running for a week now on 3 nodes with CLN 24.x. 

Log output looks normal, but I cannot rebalance any channels.  

Does circular work for anyone?

**Comment by ctrlbreak-** [comment]
No.  I've tried hundreds, if not thousands of manual circular payments with it, and it simply fails.  The closest it ever gets is finding a candidate route and apparently initiating payment, but every.single.one. times out after 120seconds.  I haven't had the opportunity to dig in further.

**Comment by giovannizotta** [comment]
The reason why circular often takes a long time to find a path is that it tries all possible paths, starting from the cheapest ones. The issue with that is that those paths are the most likely to be drained already, resulting in a lot of failures. Over time, circular learns which channels are depleted and doesn't try to go through them anymore, resulting in better success. 

Doing manual circular rebalances is not recommended, rather the idea is to wrap `circular-pull` and `circular-push` in some kind of automation that aims to maintain the desired balance on the channels. That is not offered by the plugin and since I'm not actively maintaining it, I don't plan to work on it, but I know users who have been pretty successful in rebalancing with circular after setting up some automation and turning some knobs.

I recommend to take a look at the commands `circular-pull` and `circular-push` instead of using circular directly, since that already has some automation and tries multiple routes in parallel.

If you notice circular tries the same route every time like reported by #19 , that would be a bug. If that's the case, I may take a look to try and fix it.

**Comment by Impa10r** [comment]
this project does look abandoned (((

```
$ lcli listfunds
...
   "channels": [
      {
         "peer_id": "0246ec6dc79d422a2945037afe7d0b9511a3abc6f78adae7f7419c132145381990",
         "connected": true,
         "state": "CHANNELD_NORMAL",
         "channel_id": "57b8d6f4c4661a9a7af3cf96e7e7ea6d780ce0f1abecff7bcc64c68b365e2fbf",
         "short_channel_id": "2821409x111x0",
         "our_amount_msat": 90000000,
         "amount_msat": 200000000,
         "funding_txid": "bf2f5e368bc664cc7bffecabf1e00c786deae7e796cff37a9a1a66c4f4d6b857",
         "funding_output": 0
      },
      {
         "peer_id": "02e74acffd6375fa71a038e780064ae1765ebaf520bf7b9a5681e8ff9bfe36ce29",
         "connected": true,
         "state": "CHANNELD_NORMAL",
         "channel_id": "662525f9c075509da566f652c5ecb5e6a314167ff8c9ee22482e588d20a075f7",
         "short_channel_id": "2537716x36x0",
         "our_amount_msat": 100000000,
         "amount_msat": 100000000,
         "funding_txid": "f775a0208d582e4822eec9f87f1614a3e6b5ecc552f666a59d5075c0f9252566",
         "funding_output": 0
      }
   ]
$ lcli circular -k inscid=2821409x111x0 outscid=2537716x36x0 amount=200000 maxppm=10000 attempts=1
{
   "code": -1,
   "message": "not a peer or peer channel"
}

$ lcli circular-node -k outnode=02e74acffd6375fa71a038e780064ae1765ebaf520bf7b9a5681e8ff9bfe36ce29 innode=0246ec6dc79d422a2945037afe7d0b9511a3abc6f78adae7f7419c132145381990 amount=200000 maxppm=10000 attempts=1
{
   "code": -4,
   "message": "Plugin terminated before replying to RPC call."
}

```
log:
```
panic: runtime error: index out of range [0] with length 0

goroutine 79 [running]:
circular/node.(*Node).GetBestPeerChannel(0x71fbb56838d8?, {0xc00002a5f0?, 0xc0007d0090?}, 0x91f3f0)
	/home/vlad/circular/node/peers.go:14 +0x185
circular/rebalance.(*RebalanceByNode).getBestOutgoingChannel(0xc0004a2000)
	/home/vlad/circular/rebalance/bynode.go:30 +0x2d
circular/rebalance.(*RebalanceByNode).Call(0xc0004a2000)
	/home/vlad/circular/rebalance/bynode.go:55 +0x1f3
github.com/elementsproject/glightning/jrpc2.Execute(0xc002286090, {0x998c60?, 0xc0004a2000?})
	/home/vlad/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20230525134205-ef34d849f564/jrpc2/server.go:196 +0x2a
github.com/elementsproject/glightning/jrpc2.processMsg(0xc000094bd0, {0xc00220e000, 0x122, 0x122})
	/home/vlad/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20230525134205-ef34d849f564/jrpc2/server.go:192 +0x15d
created by github.com/elementsproject/glightning/jrpc2.(*Server).listen in goroutine 1
	/home/vlad/go/pkg/mod/github.com/elementsproject/glightning@v0.0.0-20230525134205-ef34d849f564/jrpc2/server.go:120 +0x105

```

**Comment by Impa10r** [comment]
I fixed manual rebalancing in [this PR](https://github.com/giovannizotta/circular/pull/22). But push and pull don't seem to do anything:
```
~$
lcli circular-pull -k inscid=2821409x111x0 amount=2000 splits=2 splitamount=1000 maxppm=100 minoutppm=50 attempts=1 maxhops=8 filluptopercent=0.60 filluptoamount=120000
{
   "rebalance_target": 2000,
   "rebalanced_amount": 0,
   "attempts": 0,
   "time": "0.000s",
   "successes": {}
}
```

It also fails pytest:

```
=========================================================================== short test summary info ============================================================================
FAILED tests/test_circular.py::test_circular - pyln.client.lightning.RpcError: RPC call failed: method: circular-push, payload: {'outscid': '105x3x0', 'minoutppm': 0, 'amount': 100000, 'splitamount': 25000, 'maxppm': 1...
ERROR tests/test_circular.py::test_circular - ValueError:
```

 I don't use CLN in production, so don't have motivation to dig deeper. Hope @giovannizotta will find some time.
